### ISSUE TITLE
Property error in modals.styl

### ISSUE THREAD

**Issue by JimmyF4** [F4-Group/fack#1]
In the "modals.styl" file at line 35, the "transition-transform" property doesn't exist. A validation error is thrown on the w3c validator.

**Comment by jazzzz** [comment]
Wrong automated conversion of the `transition-transform` mixin from Bootstrap by [bootstrap-stylus](https://github.com/Acquisio/bootstrap-stylus), fixed in maxmx/bootstrap-stylus@0cb400db9e9deb0a2613aee98de4addde79caf78. We should upgrade.
